function phi_lap2= fun_lap2(phi,pa)
phi_lap = phi([end 1:end-1],:) + phi([2:end 1],:) + phi(:,[end 1:end-1]) ...
        + phi(:,[2:end 1]) - 4*phi;
   phi_lap2 = phi_lap([end 1:end-1],:) + phi_lap([2:end 1],:) ...
        + phi_lap(:,[end 1:end-1]) + phi_lap(:,[2:end 1]) - 4*phi_lap;